README.md, tedana/interfaces/t2smap.py
To address #10. The new function, `tedana.interfaces.t2smap.fit`, is meant to estimate T2/S0 per voxel and per volume (as opposed to estimating T2/S0 across volumes as in `tedana.interfaces.t2smap.t2sadmap`). The function `tedana.interfaces.t2smap.optcom` should also now accept 4D T2 estimate maps in addition to 3D ones.
=> [ENH] Add FIX method for estimating T2/S0

.gitignore, Dockerfile, tedana/cli/run.py, tedana/interfaces/__init__.py, tedana/interfaces/t2smap.py, tedana/interfaces/tedana.py, tedana/tests/test_tedana.py, tedana/tests/test_utils.py, tedana/utils/__init__.py, tedana/utils/utils.py
Working to add the ability to seamlessly accept gifti files in addition to nifti files.
This is still a long ways from ready, but I want to use circle testing to ensure I don't screw up anything in the process of making changes. As I'm modifying the functions to accept surface files, I'm making some stylistic changes along the way and beefing up doc-strings, as applicable.
=> [WIP, ENH] Add ability to read surface .gii files

tedana/model/fit.py, tedana/selection/select_comps.py
Progress towards #84 .
- The first half of the selcomps function is commented in much greater detail. There is more commenting and documenting work to be done in selcomps. Still, since this doesn't affect a single line of code, I figured it is better to submit a PR now, so that others can have easier access to this information.
=> [DOC] Better commenting for component selection algorithm in selcomps

tedana/model/fit.py, tedana/utils/utils.py
Closes #77.
- Remove hardcoded number of echoes from Kappa/Rho calculations.
- Remove hardcoded number of echoes from adaptive mask creation.
=> Remove hardcoded numbers of echoes.

tedana/model/fit.py, tedana/tests/test_utils.py, tedana/utils/utils.py
Closes #34.
- Drops gifti support. Images must instead be tedana-denoised before projecting to the surface.
=> [FIX] Drop gifti support

tedana/tests/test_utils.py, tedana/utils/utils.py
Closes #82.
- Reformats `load_data` to explicitly strip extensions for both zcat images and listed echo files
=> [FIX] Explicitly strip extensions

tedana/workflows/t2smap.py
- **HOTFIX !** Adds missing arguments to `t2smap`. 
- This was previously unnoticed since the `t2smap` workflow was only called in the context of the `tedana` workflow
=> [FIX] Add quiet and debug options to t2smap

.travis.yml, README.md, docs/index.rst, tedana/due.py, tedana/info.py
Closes #124.
- Specify minimum Python version in README.
- Add Python version badges tied to PyPi to README and docs index page.
- Make duecredit’s import warning sound more like a warning and less
like an error.
=> [DOC] Add Python version info

tedana/selection/select_comps.py
- Fixes leftover `if`/`else` clauses in `selcomps()` initially inserted to handle GIFTI files that checked whether input datatype was NIFTI, which broke `tedana` when BRIK/HEAD files were provided.
=> [FIX] Remove nifti requirement in `selcomps()`

tedana/workflows/t2smap.py, tedana/workflows/tedana.py
Closes: #127
- use logging.basicConfig to fix logging level
for `tedana` and `t2smap`
see: https://docs.python.org/3.7/howto/logging.html#logging-from-multiple-modules
=> [FIX] Logging in tedana and t2smap

docs/index.rst
Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Since you already use it in the citation-generating JavaScript code, this PR suggests to also update all static DOI links.
Cheers!
=> Hyperlink DOIs to preferred resolver

tedana/workflows/t2smap.py, tedana/workflows/tedana.py
Now required argument show up when tedana or t2smap help is called, via tedana -h/ t2smap -h
Closes #194 .
-required arguments show up first, in required group, when viewing tedana help
-Same solution used for t2smap
-took directly from the ~~StackExchange~~ stackoverflow - https://stackoverflow.com/a/43456577
=> [DOC] Fix arg parser

CONTRIBUTING.md, docs/contributing.rst
Doesn't close an open issue.
- Fixed broken links to code of conduct.
- This would have been a great "good first issue" but given that they're links to the code of conduct from the contributing guide in the docs and in the repo I think it's important to fix quickly! I hope that's ok 👾
=> Fix broken link to code of conduct

CONTRIBUTING.md
Closes #192 .
- In "Making a Change," adds instructions to run setup.py for developers
=> [DOC] Add tedana development setup instructions

tedana/io.py, tedana/tests/test_io.py
Closes #206  .
- in load_data, the ref image now has a 4th dimension, TR in output is now correct
-
=> [FIX] Propagate TR to ref_image header

.circleci/config.yml, tedana/decomposition/eigendecomp.py, tedana/io.py, tedana/workflows/tedana.py
References #218.
- Add options for the maximum number of iterations and restarts in ICA.
- Remove `fixed_seed` argument for `io.writeresults` and stop returning it in `tedica`.
=> [ENH] Add options to control ICA attempts

docs/api.rst, tedana/io.py, tedana/selection/_utils.py, tedana/tests/test_decay.py, tedana/tests/test_utils.py, tedana/utils.py, tedana/workflows/t2smap.py, tedana/workflows/tedana.py
Closes None. This PR will clean up the package a little bit. If we ever plan to re-integrate v3.2 into `tedana`, we can pull the removed functions from old releases. 
- Remove the following functions tied to v3.2 of the selection criteria, which we no longer support:
- `selection._utils.do_svm`
- `utils.moments`
- `utils.gaussian`
- `utils.fitgaussian`
- Remove the following functions which are outdated due to package-wide changes:
- `utils.get_dtype`: We dropped support for surfaces, so I think this is no longer necessary. It's not used anywhere in the package.
- `io.ctabsel`: We use csv/tsv files, and will use jsons, for the component tables. The old text files are no longer used.
- Remove the `minimum` argument for `utils.make_adaptive_mask`. This …
=> [REF] Clean up outdated/unused functions

tedana/viz.py
Closes #234
- change to label=kind, such that the label with match the dictionary. Should work even if we add new things to dictionary. 
- midk removed from scatter dictionary
=> [FIX] scatter plot labeling issue.

tedana/utils.py, tedana/viz.py, tedana/workflows/tedana.py
Closes #232 .
- Adds more details to title of plots, including clearly labeling component decision and rationale(s), if rejected or ignored
- trims away all zero slices prior to plotting brains, so that every figure slice contains data, rather than producing completely empty blank spaces
- Replaces bar plot with more informative pie chart
- pie chart shows total variance (outer ring) as well as individual component variance (inner ring) along with number of components in each category. 
- if some variance is unexplained, pie chart will show as well, though calculation is not perfectly accurate at this time
- a number of fixes regarding matplotlib debugging/usage mentioned by @tsalo added
- Time series and fft plots no longer have yticks - not that …
=> [ENH] Update Figure Generation Code

docs/outputs.rst, tedana/decomposition/eigendecomp.py, tedana/selection/select_comps.py
Closes None. In the process of documenting `selcomps`, I realized that I must have made a mistake when I added in table support to `selcomps`. Namely, the variable `countnoise` was not being incorporated properly in the decision tables used for certain component selection steps. `countnoise` _was_ used properly in other steps, so I think the impact is minimal.
- Remove `countnoise` variable from `selcomps`. When we switched over to using tables, I forgot to remove this variable, so it was being initialized as an array of zeros but wasn't filled out (because the associated column of `comptable` was). `countnoise` was only used in the decision table steps, so it was essentially being ignored as a metric there.
- Add some documentation about the …
=> [FIX, DOC] Use countnoise in decision table within selcomps

tedana/gscontrol.py, tedana/io.py, tedana/model/__init__.py, tedana/model/fit.py, tedana/tests/test_gscontrol.py, tedana/workflows/tedana.py
Closes None.
- Move gscontrol_raw and gscontrol_mmix into new gscontrol module. They are currently in model.fit and io, respectively, which are not good places for them.
=> [REF] Add gscontrol module

tedana/workflows/tedana.py
Closes #243.
- Make a copy of the mixing matrix before orthogonalizing if `tedort` and use that one for figure-making.
=> [FIX] Make figures using un-orthogonalized mixing matrix

tedana/decomposition/eigendecomp.py, tedana/gscontrol.py, tedana/io.py, tedana/model/fit.py, tedana/selection/select_comps.py, tedana/viz.py, tedana/workflows/tedana.py
Also fix up docstrings and eliminate step where component number is set
as a column. Always keep it as the index of the DataFrame.
Closes None.
- Use comptable DataFrame instead of lists of components in tedana.io
- Clean up docstring documentation of comptable throughout tedana
- Eliminate step where component number is set as a column. Always keep it as the index of the DataFrame.
- Use more concise methods for indexing DataFrames (e.g., `comptable[comptable.classification == 'acc'].index.values` instead of `comptable.loc[comptable['classification'] == 'acc'].index.values`).
=> [REF] Clean up comptable handling in tedana.io

tedana/model/__init__.py, tedana/model/fit.py, tedana/utils.py
Closes None.
- Use `numpy.unique` to cluster-extent threshold and binarize maps with `spatclust`.
- Cluster positive and negative values separately.
- Rename `spatclust` to `threshold_map` and move from `model.fit` to `utils`.
- Add arguments for binarization (default is yes) and sided-ness of the thresholding (default is to treat positive and negative values the same).
=> [ENH] Speed up cluster-extent thresholding function

tedana/selection/select_comps.py
Closes None. This was originally part of #247, but has been split off because it is self-contained and should be merged separately.
At one point, the d_table_score metric is used when d_table_score_scrub should have been used. This is a minor bug.
- Replace `d_table_score` with `d_table_score_scrub` in one instance.
=> [FIX] Fix use of d_table_score

docs/approach.rst, tedana/combine.py, tedana/decomposition/eigendecomp.py, tedana/model/fit.py, tedana/tests/test_combine.py, tedana/tests/test_t2smap.py, tedana/workflows/t2smap.py, tedana/workflows/tedana.py
Closes #210, #214. This was originally part of #247, but has been split off because it is self-contained and should be merged separately.
- Rename `combmode` value “ste” to “paid”
- Rename variable `ste` to `source_tes` for clarity
- Drop PAID support from tedana (because PAID requires smoothed data and multi-echo denoising does not work with smoothed data) but keep it in t2smap workflow
- Add note box about PAID to documentation
=> [REF, DOC] Document PAID combination method

CONTRIBUTING.md
Addresses (but does not complete #270)
- Add dev calls & calendar to contributing guidelines
Happy to move this to a different part if that would be better? Let me know what you think's best 😸
=> Add dev calls to contributing guidelines

docs/outputs.rst, tedana/selection/select_comps.py, tedana/workflows/tedana.py
Closes None. This was originally part of #247, but has been split off because it is self-contained and should be merged separately.
- Allow users to re-run tedana on the same directory without raising copyfile errors.
- Retain original classification and rationale when manually overriding classification.
- Allow `manacc` to be a list to make it easier to run within Python.
- Clean up logic around checking mixm, ctab, and manacc arguments.
=> [ENH] Improve manual component selection

tedana/workflows/tedana.py
Closes #193 .
- Fixes random seed help text
=> [DOC] Fixes Random Seed Help Text

tedana/selection/tedica.py
Closes #176. While this does not clarify everything about this step (e.g., why it is run three times specifically, or why the outlier components are excluded when computing elbows but not when selecting components later), it does resolve the most pressing issue of explaining why the step exists.
This was originally part of #247, but has been split off because it is self-contained and should be merged separately.
- Sort component table when identifying ncls (components presumably without outlier variance explained) by descending variance explained. Before, the component table was sorted by descending Kappa values when identifying outliers. Per discussions with @handwerkerd, this was identified as a bug.
=> [FIX] Sort comptable by varex before identifying outlier components

tedana/selection/tedica.py
Closes #297.
- Add early stopping procedure to TEDICA decision for when no potential BOLD components are identified in Step 1.
=> [FIX] Add early escape from TEDICA decision tree

CONTRIBUTING.md
Progress on #259 
- Adds all-contributors spec and notes bot usage
=> [DOC] Updates CONTRIBUTING to reflect contribution spec and bot

tedana/decomposition/pca.py, tedana/io.py, tedana/metrics/kundu_fit.py, tedana/stats.py, tedana/utils.py, tedana/workflows/tedana.py
References #269. I very much doubt that these changes will solve the problem on their own, and I'm not even sure if they'll help much.
- Add `--lowmem` argument to trigger use of IncrementalPCA. Should also trigger other low-memory steps we might implement in the future.
- Clean up arrays in `dependence_metrics` when they're no longer used.
- Operate on masks arrays as much as possible within `dependence_metrics`.
- Make `mask` argument for `computefeats2` optional.
=> [ENH, REF] Reduce memory requirements for metric calculation and PCA

.circleci/tedana_outputs.txt, tedana/decomposition/pca.py, tedana/metrics/kundu_fit.py
Closes #363.
- Switch from using `dependence_metrics`-based variance explained estimates (which sum to 100 and thus break the `kundu-stabilize` decision tree) to using the PCA-based ones.
- Retain `dependence_metrics`-based variance explained estimates as "estimated normalized variance explained" in component table. This also removed "original normalized variance explained", which was the PCA-based values (now just "normalized variance explained").
- Make `dependence_metrics`-based variance explained estimates sum to 1 instead of 100, just so that "normalized variance explained" remains a relatively consistent measure across implementations.
- Use `ppca.explained_variance_ratio_` instead of `ppca.explained_variance_` to calculate normalized variance …
=> [FIX] Use PCA-based variance explained in PCA decision tree

.circleci/config.yml
Closes #388 .
- Installs curl where needed
-
=> [FIX][TST] Adds curl installation where needed

README.md, setup.py, tedana/info.py
- Add `python_requires` metadata, matching the Python classifiers
- Require numpy >= 1.14, as indicated in #141
Closes #395.
Closes #396.
=> MAINT: Update numpy and Python requirements

tedana/workflows/tedana.py
Hello,
This PR is a solution for #361, as discussed with @tsalo.
The changes are :
- make `--debug` visible in the help
- added some *help* documentation about this `--debug` option
- this `--debug` option is is now the default behavior
For now, I see 2 drawbacks that can easily be fixed :
1) changing the behavior so the option can be controlled : `--debug yes/no`
**and / or**
2) create a new option separate such as `--report` or `--log` and separate if from the `--debug` option
What do you think ?
Best,
Benoît
=> [ENH] --debug flag appear now in the help & documentation

.circleci/config.yml, dev_requirements.txt, requirements.txt
Closes # .
- Adds building of docs to CircleCI (and stores them as artifacts)
- Migrates a few things from `requirements.txt` to `dev_requirements.txt` related to doc building
- Moves some python environment building around in CircleCI config
=> [WIP,TEST,DOC] Builds docs in CircleCI

tedana/tests/test_integration.py, tedana/workflows/tedana.py
Closes None
- Prevents shell-expansion in Python, which is allowed bi `nilearn` but concatenates the data in time, which is incorrect. 
-
=> [FIX] Prevents shell expansion in API

.circleci/config.yml, Makefile, dev_tools/run_tests.sh
Closes None
- Runs integration tests in parallel
- Removes doc building in CircleCI
=> [ENH][TST] Feature/parallel integration

tedana/selection/tedica.py
Closes #462. This fixes a bug that impacts component selection in unclear ways, although the overall step will be replaced in the near future.
- Calculate the difference in variance explained for each component to the component after it (rather than before it, as implemented now).
- Fill NaNs with zeros.
=> [FIX] Fix variance explained outlier detection

docs/outputs.rst, tedana/decay.py, tedana/tests/data/tedana_outputs.txt, tedana/tests/data/tedana_outputs_verbose.txt, tedana/tests/test_decay.py, tedana/workflows/t2smap.py, tedana/workflows/tedana.py
Closes #440 and closes #439.
- Split the actual decay-fitting parts of `decay.fit_decay` into `fit_loglinear` and `fit_monoexponential`.
- Only fit curve to voxels that will be used in the limited or full S0/T2* maps. This should speed up curve-fitting with large number of echoes.
- Remove ascending T2*/S0 estimates from `fit_decay` outputs.
- Write out adaptive_mask.nii.gz by default.
=> [REF] Reorganize fit_decay

tedana/info.py
The versioneer package is not a requirement to use versioneer, only to update it. `install_requires` should only list packages needed to use the package, not to maintain it. If you like, I could add a `dev` extra that includes versioneer.
Context: fMRIPrep indirectly requires versioneer because it requires tedana. I'd rather keep the dependencies to a minimum.
- Removes the versioneer package from `install_requires`.
=> [MNT] Drop versioneer from requirements

tedana/decomposition/pca.py, tedana/workflows/tedana.py
Closes #485.
- Remove all instances of `sourceTEs` and `source_tes`.
=> [REF] Remove the sourceTEs option

tedana/metrics/kundu_fit.py, tedana/stats.py
Closes # .
- Adds some more comments explaining some steps to computfeats2
-
=> [DOC] Improve documentation of computefeats2

.github/stale.yml
Closes #528.
- Increase time between when `stale` label is added and issue is automatically closed from 7 days to 600 days.
- Have stalebot ignore issues labeled with "bug", "paused", or "good first issue" (in addition to "community", which was already ignored).
=> [REF] Reduce stalebot aggression

tedana/tests/test_integration.py, tedana/workflows/tedana.py
Closes #541.
- Removes colons from the log-file's filename, for Windows compatibility.
- Changes variable `isotime` to `start_time`, to reflect that the string is no longer in ISO format.
- Updates regular expression in `test_integration` used to find and remove the log-file based on the new filename structure.
=> [FIX] Remove colons from log filename

tedana/tests/test_integration.py, tedana/tests/test_t2smap.py
Closes None.
- Swap re-runs in the integration tests from using `tedana.workflows.tedana.tedana_workflow` to `tedana.workflows.tedana._main` (i.e., the CLI).
- Add new t2smap unit test that uses `tedana.workflows.t2smap._main`.
=> [TST] Add tests for the workflow CLIs

docs/approach.rst
Closes #547.
- Removes the MLE description from the TEDPCA section in the docs.
- Adds the MA-PCA description to the TEDPCA section in the docs.
=> [DOC] Updates the TEDPCA section following changes in tedana v0.0.8

docs/approach.rst
Closes # .
- Adds missing change missing in #551.
=> [DOC] Adds PCA documentation change that was missing

tedana/decomposition/pca.py
Closes #490. This acts as a quick fix for the PCA masking issue, but we will ultimately use the outlier-based mask (i.e., `eimask`) in the adaptive masking procedure at the beginning of the workflow (see #491).
- No longer use eimask at all.
=> [FIX] Drop use of eimask

.github/stale.yml
Closes None. This is an extremely minor change, impacting only the message posted by stale-bot. I noticed that the message posted when the stale label is added doesn't include the time frame before the issue will be closed. This just incorporates that information into the message.
- Include daysUntilStale and daysUntilClose in stale-bot message.
=> [REF] Include daysUntilStale and daysUntilClose in stalebot message

tedana/tests/test_t2smap.py, tedana/workflows/t2smap.py
References #540. This is currently limited to the t2smap workflow because the focus is on fMRIPrep compatibility, but I can also rename the output files in the tedana workflow as well, if folks want.
- Change output files for t2smap_workflow and corresponding outputs in tedana_workflow to be more BIDS-like:
- t2sv.nii --> T2StarMap.nii.gz
- s0v.nii --> S0Map.nii.gz
- t2svG.nii --> desc-full_T2StarMap.nii.gz
- s0vG.nii --> desc-full_S0Map.nii.gz
- ts_OC.nii --> desc-optcom_bold.nii.gz
- Add out-dir argument to t2smap_workflow, defaulting to CWD.
=> [REF] Update t2smap workflow for fMRIPrep compatibility

tedana/tests/test_t2smap.py, tedana/workflows/t2smap.py
Closes None. I was reading the BEP001 supported extensions list and realized I made a mistake in #557. This will fix that.
- In the `t2smap` workflow: T2StarMap --> T2starmap
- In the `t2smap` workflow: S0Map --> S0map
=> [FIX] Correct t2smap outputs

tedana/decay.py, tedana/tests/test_decay.py
Closes #513.
Todo:
- Add a new function to determine smallest non-zero T2* value that will not resolve to zero in optimal combination step. Replace values in the T2* maps > 0 and < this value with the value.
- Add a new unit test for the function. This test doesn't improve coverage, but is important.
=> [FIX] Add non-zero floor to T2* values

Makefile, setup.cfg
Closes None.
- Show info-level logging output during integration tests.
=> [TST] Show logging output during integration tests

tedana/info.py
Closes #472.
- Uses the README text as the package "long description," which currently reads as "To do."
- The long description can be [seen on PyPi here](https://pypi.org/project/tedana/).
=> [DOC] Use README as long_desc

tedana/tests/test_integration.py, tedana/workflows/tedana.py
Closes #563.
- Switch manacc from comma-delimited string to list of integers.
- Update affected integration test.
=> [ENH] Use list of ints for manacc instead of comma-separated string

.github/ISSUE_TEMPLATE/issue_template.md, docs/support.rst
Closes #593 .
- Update support.rst file to include tedana tag link. 
- _Question:_ Should we also edit Line 7 to say "If you would like ... ``tedana`` tag." instead of "... ``multi-echo`` tag." ?(@jbteves and I were wondering this, given that we now want to point tedana-specific questions to the tedana tag).
-
-
=> [DOC] Added link for tedana NeuroStars tag.

docs/api.rst, docs/approach.rst, tedana/gscontrol.py, tedana/tests/data/fiu_four_echo_outputs.txt, tedana/tests/test_integration.py, tedana/workflows/tedana.py
Closes #605.
- Rename function name, variables, and output files for T1c global signal regression to match new designation as "minimum image regression."
- Change multiline string-based comments to regular comments.
- Clean up some steps (e.g., z-scoring of arrays) in the function.
=> [REF] Rename T1c to "minimum image regression"

.zenodo.json
Closes #612.
- Add all contributors to Zenodo file.
- Reorder Zenodo contributors in file alphabetically by last name.
=> [MAINT] Add all contributors to Zenodo file

tedana/reporting/dynamic_figures.py
Closes #582.
- Add a diagonal line (y = x) in kappa/rho scatter plot to make it easier to identify which of the two is greater for each component
---
Other notes:
- Here's what the figure looks like the for the three test datasets
- The above scatter plots do not match the ones in the [three-echo](https://me-ica.github.io/tedana-ohbm-2020/three-echo-report/tedana_report.html) and [five-echo](https://me-ica.github.io/tedana-ohbm-2020/five-echo-report/tedana_report.html) reports from an older run
+ Assuming the older run used the same data, the differences could be due to changes in the code (#622) or if different input arguments were used
- Perhaps a bit more troubling: I got different results by changing the python environment. Gif below shows the …
=> [ENH] Add diagonal reference line to kappa/rho plot

.all-contributorsrc
Closes #628 
- Deploys CI for all-contributors so we can review it like normal pull requests
=> [TST] Allow CI for all-contributors

tedana/workflows/tedana.py
Closes #606.
- Instead of removing all handlers from `logging.root` at the end of the worklow, only remove `sh` and `log_handler`
+ The root logger contains other handlers if pytest is being used, and one of those handlers is responsible for printing to the terminal, so we don't want to remove these handlers.
- Manually add handlers to `logging.root` instead of using `logging.basicConfig()`
+ `basicConfig` does nothing if `logging.root` already has handlers
+ `logging.root` will have no handlers if a user is calling tedana, but it does have handlers if pytest is being used
+ In the current tests, `basicConfig` does nothing in the first run because `logging.root` already has handlers, but then these handlers are deleted at the end of the first run. On …
=> [FIX] Show logs in re-runs

tedana/decay.py
Closes None.
- Fill in the missing docstring for `tedana.decay.fit_loglinear()`.
- Fix docstring for `tedana.decay.fit_decay()`. The notes were out of date.
- Fill out parts of docstring for `tedana.decay.fit_monoexponential()`.
=> [DOC] Add docstring to fit_loglinear

tedana/combine.py, tedana/decay.py
Closes #638.
- Add a `report` argument to relevant functions so that we can toggle whether a given function will add to the report logger. In cases where the same function is called multiple times, we turn the report off.
=> [FIX] Eliminate duplicate lines in logs

tedana/decay.py
Closes #589.
- Count number of voxels being floored in T2* estimation, then log it.
=> [DOC] Log count of floored voxels in T2* estimation

docs/outputs.rst
=> [DOC] Clarify role of components in docs

tedana/combine.py, tedana/decay.py, tedana/decomposition/pca.py, tedana/metrics/kundu_fit.py, tedana/tests/test_utils.py, tedana/utils.py, tedana/workflows/t2smap.py, tedana/workflows/tedana.py
References #617.
- Add threshold argument to `make_adaptive_mask`.
- Hardcode threshold at 1 for the t2smap workflow and 3 for the tedana workflow.
- When deriving the binary mask from the adaptive mask, change threshold from 3 to 0 (basically assuming that the adaptive mask is thresholded).
- Improve associated documentation a bit.
- Update the `make_adaptive_mask` test.
=> [ENH] Add threshold argument to make_adaptive_mask

tedana/decomposition/ica.py, tedana/tests/data/fiu_four_echo_outputs.txt, tedana/workflows/tedana.py
Closes #662. This is just a first pass, although I think it should work.
- Re-run ICA (within constraints of `maxrestarts` parameter) when no BOLD components are found by the decision tree.
=> [ENH] Add ability to re-run ICA when no BOLD components are found

.github/pull_request_template.md, CONTRIBUTING.md, README.md, docs/contributing.rst, docs/developing.rst, docs/governance.rst, docs/index.rst, docs/sphinxext/github_link.py, tedana/due.py
Addresses but does not close #619 .
- Switch `master` to `main` where applicable
-
NOTE: due to versioneer and the document doc tree, there are some references to `master` that cannot be changed from my read. All examples below:
```
docs/conf.py:67:# The master toctree document.
docs/conf.py:68:master_doc = 'index'
docs/governance.rst:184:`decision-making rules for the BIDS standard <https://github.com/bids-standard/bids-specification/blob/master/DECISION-MAKING.md>`_,
tedana/_version.py:192:        # "stabilization", as well as "HEAD" and "master".
versioneer.py:18:(https://travis-ci.org/warner/python-versioneer.png?branch=master)
versioneer.py:179:  "master" and "slave" subprojects, each with their own `setup.py`,
versioneer.py:612:        # …
```
=> [REF] Replaces master with main where possible

setup.py, tedana/__init__.py, tedana/info.py
References #668 
The `README.md` file is used as the module's long description. The relevant code is defined in `tedana/info.py`. This causes an error when importing the module because it tries to load the readme file, but the readme file does not get copied over once the module is installed
This PR moves the relevant code to `setup.py` so that the readme file is only read when the module is first being installed. This should get rid of the error. Remains to be seen if the long description will correctly show up on pypi.
=> Move long description logic from info.py to setup.py

.zenodo.json, README.md, tedana/tests/test_integration.py
Closes None.
Few small changes:
- Use platform-specific path when comparing output files in integration tests
+ This was causing tests on Windows to fails because it expects `paths\like\this` instead of `/like/that`
- Updated the number of contributors on the readme badge
+ There is a [configuration option](https://github.com/all-contributors/all-contributors/blob/master/docs/bot/configuration.md) which might automatically do this
+ Looks like there is a mismatch in the number of total contributors between all-contributors and [github's contributor list](https://github.com/ME-ICA/tedana/graphs/contributors). I went with number of all-contributors.
- Added myself to `.zenodo.json`
+ Should this follow the order in the planned JOSS paper? That might be better for consistency, but that means …
=> [MAINT] Support Windows' paths; Update zenodo & contributor count

CODE_OF_CONDUCT.md, CONTRIBUTING.md, tedana/__init__.py, tedana/info.py
Closes #631.
- Swap @emdupre for the CoC team in the code of conduct document.
Additional changes to consider:
- Switching the __maintainer__ field in `info.py`
- Adding emails for CoC team instead of directing to their GitHub profiles.
=> [DOC] Harmonizes Governance Documents

tedana/reporting/data/html/report_head_template.html, tedana/reporting/html_report.py
Closes none.
Context: There are two bokeh libraries: one is in python, the other in javascript. Ideally, they should both be the same version. Currently, the javascript version is pinned at 2.0.1 in the html report. This can create a conflict if the user has a different python version of bokeh.
- Dynamically set the javascript version of bokeh to match the python version
=> [ENH] Match BokehJS with BokehPy version

tedana/decomposition/pca.py
Closes none.
The results for the three-echo test changed when the `mapca` library was added:
- [before](https://13314-110845855-gh.circle-artifacts.com/0/tmp/data/three-echo/TED.three-echo/tedana_report.html)
- [after](https://13347-110845855-gh.circle-artifacts.com/0/tmp/data/three-echo/TED.three-echo/tedana_report.html)
- EDIT: [this PR](https://13446-110845855-gh.circle-artifacts.com/0/tmp/data/three-echo/TED.three-echo/tedana_report.html)
This might be because the data is no longer being normalized. This PR sets `normalize=True` when calling `ma_pca`, and hopefully that should match the old results.
=> [FIX] Enable normalization in mapca call

tedana/workflows/tedana.py
Closes #686.
- Generate HTML reports _after_ the text is cleaned up and references are added to `report.txt`. This results in the references being included in HTML reports.
=> [DOC] Add references to HTML report

tedana/metrics/kundu_fit.py
Closes #710 .
- Threshold F-maps before making derivative metrics, rather than just before kappa/rho calculation
-
=> [FIX] Adds f_max to right place

tedana/metrics/kundu_fit.py, tedana/tests/data/fiu_four_echo_outputs.txt
Closes #713, which was probably introduced in #358.
- Calculate Rho and Kappa from the F-statistic maps compiled across adaptive mask values, instead of maps where only voxels where adaptive mask == number of echoes are filled in.
=> [FIX] Calculate Kappa and Rho on full F-statistic maps

docs/contributing.rst
Closes None.
- Add a warning box about not directly releasing release-drafter release drafts (😆).
A screenshot:
=> [DOC] Add warning about not using release-drafter releases to developer instructions

docs/conf.py
Closes #726 .
- Renames two `sphinx` functions that have been renamed (probably after an update).
=> Rename sphinx functions to fix building error for docs

tedana/workflows/tedana.py
Closes None, but reimplements #695, which we somehow reverted at some point.
- Move HTML report/figure generation section of workflow to _after_ the point where references are merged into the text report.
=> [FIX] Add references back into the HTML report

tedana/workflows/tedana.py
Closes #738.
- Disable report logger (`RepLGR`) during ICA restart loop, then re-enable after the while loop is exited.
=> [FIX] Disable report logging during ICA restart loop

docs/support.rst
Closes #478.
- Add section in Support and Communication page on how and when each of the established communication pathways should be used.
=> [DOC] Clarify communication pathways

docs/resources.rst
Addresses #552 and closes #633.
- Added a new section to the resource page to introduce and link to the Dash app for visualizing study parameters and MRI sequence parameters. NOTE: when adding a new section below the iframe for the google sheet, this section wouldn't render when building locally. To circumvent this, I added the new section above the iframe, and updated the reference to the sheet in the "Publications using multi-echo fMRI" section, to point to it being at the bottom of the page. If anyone feels there's a more intuitive way of ordering these sections and iframe on the resource page, feel free to update.
- Added the `rt-me-fMRI` dataset link to the list of open datasets.
=> [DOC] Update resource page with dataset and link to Dash app visualizations

tedana/decomposition/pca.py, tedana/metrics/_utils.py, tedana/metrics/collect.py, tedana/tests/test_metrics.py, tedana/workflows/tedana.py
Closes #564.
**NOTE**: While the proposed changes do affect the order of rows in the component table and the mixing matrix, they should not impact the actual classifications at all.
I have one question- should we also eliminate the component flipping step? I'm thinking specifically that we could (1) keep components with the same signs in our outputs, but (2) add a new "flip" column to the metrics TSV indicating if the component was flipped prior to calculating metrics. Then, the mixing matrix would not be changed at all by `tedana`, but the results would be the same. The only things that would change would be the saved weight maps and the signs of the maps in the report. We could even use the "flip" column in the report figure generation to retain the preferred signs.
To do:
- Opened …
=> [REF] Eliminate component sorting from metric calculation

tedana/decomposition/pca.py, tedana/metrics/_utils.py, tedana/metrics/collect.py, tedana/reporting/static_figures.py, tedana/tests/test_metrics.py, tedana/workflows/tedana.py
Closes #748.
- Add new metric, "optimal sign", to component tables.
- Do not return sign-flipped mixing matrix from `metrics.collect.generate_metrics()`.
- Write out _unmodified_ mixing matrix in main workflow.
- Coerce signs to integers rather than floats. This will make the metric values in the component table easier to interpret.
=> [REF] Do not modify mixing matrix with sign-flipping

tedana/workflows/tedana.py
Closes #753.
- Describe mutually dependent parameters in argument parser and workflow docstring.
- Check that both ctab and mmix are provided if manacc is, rather than just checking for mmix.
=> [FIX] Correct manacc documentation and check for associated inputs

tedana/io.py
Closes #757  .
- Downscales 64-bit float, int arrays to 32-bit arrays just before image save
- Adds some notes to the `io.save_img` docstring
=> [ENH] Coerce images to 32-bit

tedana/selection/_utils.py, tedana/selection/tedica.py, tedana/tests/test_selection_utils.py
Closes #752. In the ICA decision tree, there is a step where two elbows are calculated: one from all kappa values and one from non-significant kappa values. When there are no non-significant kappa values, this step fails.
- Ignore the non-significant kappa value-based elbow when there are no non-significant kappa values. Log a warning about this when it comes up.
- For any other cases where `getelbow` or `getelbow_cons` fail, raise a more informative exception and include in that message a request to open an issue here.
- Add new smoke test for `getelbow` and `getelbow_cons`.
=> [FIX] Ignore non-significant kappa elbow when no non-significant kappa values exist

README.md, docs/installation.rst, tedana/info.py
Closes #761  .
- Updates minimum version requirements for python dependencies in tedana/info.py to match nilearn>=0.7
- Removes minimum version requirements from docs/installation.rst & README.md so those will only need to be updated in one place
=> [DOC, MAINT] Updated dependency version numbers

setup.py
Closes None. I was just testing a new install from the `main` branch and got the following:
```
Traceback (most recent call last):
File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/processing/04_run_multi-echo_denoising.py", line 255, in <module>
run_tedana(project_dir, dset)
File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/processing/04_run_multi-echo_denoising.py", line 127, in run_tedana
prefix=prefix,
File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/tedana/workflows/t2smap.py", line 220, in t2smap_workflow
make_figures=False,
File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/tedana/io.py", line 84, in __init__
config = load_json(config)
File …
```
=> [FIX] Add resources folder to package data

docs/faq.rst, docs/multi-echo.rst, docs/usage.rst
Closes #717.
- Add information about collecting fMRIPrep data (with gist) to FAQ.
- Link to new FAQ in other sections.
=> [DOC] Add fMRIPrep collection information to FAQ

docs/api.rst, tedana/io.py, tedana/tests/test_io.py, tedana/tests/test_utils.py, tedana/utils.py, tedana/workflows/tedana.py
Closes #801.
- Explicitly check input against valid types in `load_data`. This will raise an exception when a tuple is provided, rather than silently treating the tupled files as a single z-cat file.
- Fix the `load_data` docstring, which was out-of-date.
- Rename `utils.load_image` to `utils.reshape_niimg`. While this function does support image loading, its primary purpose is to reshape `X x Y x Z [x T]` data to `S [x T]`.
=> [FIX] Check data type in `io.load_data`

tedana/decay.py
For 5 echo data, I was noticing the following warning:
```
INFO     tedana:tedana_workflow:584 Computing T2* map
/Users/handwerkerd/code/tedana_community/me-ica/tedana/tedana/decay.py:40: RuntimeWarning: divide by zero encountered in true_divide
temp_arr = np.exp(-echo_times / t2s)  # (E x V) array
INFO     combine:make_optcom:242 Optimally combining data with voxel-wise T2* estimates
```
This warning was created by #736 when it became possible to to send a t2s volume with 0's to  `_apply_t2s_floor` The function correctly ignored voxels where t2s was zero, but only after dividing by t2s and triggering this warning
- Edited  `_apply_t2s_floor` so that voxels with 0 in t2s are excluded from the denominator when dividing
=> [FIX] Address divide by 0 issue in decay.py

tedana/reporting/dynamic_figures.py
Closes # .
This is a very minor bug fix that makes the 0-padding in the report Javascript code more robust. Specifically, the component figures didn't display correctly for any components > 99 since they were padded to 0100, 0101 etc instead of just 100. 
-
-
=> [FIX] Fixes broken component figures in report when there are more than 99 components

docs/index.rst
- Changed markdown link to RST in `index.rst`.
=> DOC: Use RST link for ME-ICA

tedana/workflows/tedana.py
Closes #854 .
- Check that the given `ctab` is Rica's by looking at the column names.
- Update the rationale of `comptable` with `selection.manual_selection(comptable, acc=manacc)`.
=> [FIX] The rationale column of comptable gets updated when no manacc is given

docs/approach.rst, tedana/decomposition/pca.py, tedana/tests/data/cornell_three_echo_outputs.txt, tedana/tests/test_integration.py, tedana/workflows/tedana.py
Closes #843 .
- Updated all references to the default maPCA option from `mdl` to `aic`.
- Made `aic` the default maPCA option.
- Updated three-echo test to use `aic`.
=> Made AIC the default maPCA option

tedana/tests/test_integration.py, tedana/workflows/tedana.py
Closes #848.
- Add a manual classification step in the four-echo integration test that uses the component table for the classifications.
- Change the classifications in the five-echo integration test's manual classification step.
- Add a logger message when a component table is provided.
=> [DOC] Improve logging of component table-based manual classification

tedana/info.py
Closes #869  .
- Pins jinja2 version as a workaround
-
=> [FIX] Add jinja2 version pin as workaround

CONTRIBUTING.md
Closes #844, #845
- `pip install -e .'[all]'` does not work on Windows while `pip install -e .[all]` does. This changes CONTRIBUTING.md to recommend this step without the added quotes.
=> [DOC] Generalize installation instructions to work with Windows in CONTRIBUTING

tedana/decomposition/pca.py, tedana/tests/test_workflows_parser_utils.py, tedana/workflows/parser_utils.py, tedana/workflows/tedana.py
Closes #876.
- We changed AIC to the default PCA selection criterion in #849 for the API. I noticed it was still defaulting to MDL for the command line interface, so I fixed that
- As discussed in #876, normalized variance explained was calculated one way for mdl, kic, & aic, and a different way for the low_mem option or if a specific variance explained as selected. Everything now matches the calculation used for mdl, kic, & aic
- The sum of the normalized variances across PCA components is the % variance of the original data that's explained by the PCA according to the PCA function in sklearn. I am now including this value in the info logger. It doesn't match the percent variance explained values that are given as later outputs. Figuring out how to …
=> [ENH, FIX] PCA variance enhancements and consistency improvements

.gitignore, docs/conf.py, docs/faq.rst
Closes None.
- Add information about fMRIPrep's new `--me-output-echos` parameter.
- Add instructions for applying fMRIPrep's transforms to warp native-space data to standard space.
- Fix a couple of small bugs in the documentation.
=> [DOC] Add information about using tedana with fMRIPrep v21.0.0

docs/outputs.rst, tedana/metrics/collect.py, tedana/resources/config/outputs.json, tedana/tests/data/fiu_four_echo_outputs.txt, tedana/tests/data/nih_five_echo_outputs_verbose.txt
Closes #891.
- Add PCA and ICA F-statistic maps for the T2* and S0 models (for each component) to verbose outputs.
=> Add F-T2 and F-S0 maps to verbose outputs

tedana/io.py, tedana/selection/_utils.py, tedana/selection/tedica.py, tedana/tests/test_selection_utils.py, tedana/tests/test_utils.py
Closes #923
- Fixes bug in the decision tree where variance explained should have been sorted before calculating a percentile for a subset of components.
- The relevant decision tree step used code I011.
- With this change, the variance threshold will be higher and a few more components may end up as `accepted` rather than `ignored` This won't affect the denoised time series since either classification is retained in the denoised time series.
- Also changed an `np.int` to `np.integer` in `_utils.py` that was causing tests to fail in CI, but not locally.
=> Sorting varex for decision tree criterion I011

docs/contributing.rst
Closes None .
- Removes my status as maintainer, steering committee member, collaborative programming lead, and communications leader.
Thanks for all of the good times!
=> [DOC] Remove Josh as maintainer

.zenodo.json, tedana/io.py
Closes #935 by adding 
Ultimately needed a way to check pandas version, if it's above 1.5 then the parameters for to_csv are different. Did two things:
1. Added a version check function 
```
def versiontuple(v):
return tuple(map(int, (v.split("."))))
```
2. Added conditional to `save_tsv`
```
if versiontuple(pd.__version__) >= versiontuple("1.5.2"):
data.to_csv(name, sep="\t", lineterminator="\n", na_rep="n/a", index=False)
else:
data.to_csv(name, sep="\t", line_terminator="\n", na_rep="n/a", index=False)
```
Someone should probably write more tests for this. However I did run on my system and confirm that it runs now successfully on pandas 2.0.0 (and 1.5.2).
=> add pandas version check >= 1.5.2 and mod behavior

tedana/decomposition/pca.py
Once https://github.com/ME-ICA/mapca/pull/57 is merged into MAPCA, it will be possible for tedana to log the estimated subsampling value and several related parameters.
- Logs several values related to the IID subsampling estiamte that are related to `desc-PCACrossComponent_metrics.json`
- A few PCA-related documentation changes that were noticed when writing this PR
I decided to add a conditional statement to only log these new values if they exist. The alternative is, once the above PR is merged into MAPCA, we release a new version of MAPCA and then update the minimum MAPCA version allowed with tedana. I'd rather just merge for now and then we can delete the conditional in the same PR where the minimum version of MAPCA is increased.
=> logging MAPCA subsampling

pyproject.toml, tedana/selection/selection_utils.py, tedana/workflows/ica_reclassify.py
Closes #967, Closes #961
- Uses `type(a) is list` instead of `type(a) == list`.
- Increases the minimum version required for sphinx to 6.2.1 and sphinx_rtd_theme to 1.2.2, which should not use the removed mention of style.
=> [FIX] Styling issues and make RTD build work

tedana/decay.py
- remove copy of the data that seems unnecessary, cuts memory usage by ~30%
- data is not modified afterward, is copied through subsetting in the following lines (362).
investigation of memory usage originates from https://github.com/nipreps/fmriprep/issues/3125
=> remove unecessary copy of large data

pyproject.toml, tedana/reporting/dynamic_figures.py
I looked at #869 and #766 and I think I roughly understand the problems they were trying to fix. I think the jinja2 one was a short-lived incompatibility that just removing it should fix. The other one appeared to affect the reports. Running `make three-echo` in an environment with the latest bokeh produced one complaint that resolved to https://github.com/bokeh/bokeh/issues/12543, and otherwise just worked.
Closes #976.
=> MNT: Uncap dependencies

.circleci/config.yml, docs/conf.py, pyproject.toml, tedana/__init__.py, tedana/bibtex.py, tedana/io.py, tedana/reporting/html_report.py, tedana/selection/component_selector.py, tedana/selection/selection_nodes.py, tedana/selection/selection_utils.py, tedana/tests/test_combine.py, tedana/tests/test_component_selector.py, tedana/tests/test_decay.py, tedana/tests/test_integration.py, tedana/tests/test_io.py, tedana/tests/test_selection_nodes.py, tedana/tests/test_stats.py, tedana/tests/test_utils.py, tedana/workflows/ica_reclassify.py, tedana/workflows/tedana.py
Add GitHub tests for Python 3.11 and 3.12, updating pyproject.toml to reflect support.
While I'm at it, I updated the `black` target version to Python 3.8 and ran `pyupgrade --py38-plus`.
For reference, [pyupgrade](https://github.com/asottile/pyupgrade) is a small tool to migrate to new syntax or best practices as support windows drop older versions of Python.
=> MNT: Test on 3.11 and 3.12

tedana/workflows/ica_reclassify.py
R. Miller at BCBL messaged that he noticed some typos. This corrects them.
- In `ica_reclassify` `--manrej` now `rejects` rather than `accepts` components and `liist` typo is correcte
=> Fixing ica_reclassify CLI documentation typo

tedana/workflows/ica_reclassify.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [ica_reclassify.py](https://github.com/ME-ICA/tedana/blob/main/tedana/workflows/ica_reclassify.py#L544), method: `ica_reclassify_workflow`, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. iCR suggested that the logical operation should be reviewed for correctness.
Running the program below will give the output-
```python
foo = []
print(foo is [])
print(foo == [])
```
```
False
True
```
*This section is only …
=> Fixed Inappropriate Logical Expression

tedana/reporting/data/html/report_info_table_template.html, tedana/reporting/html_report.py, tedana/tests/data/nih_five_echo_outputs_t2smap.txt, tedana/utils.py, tedana/workflows/ica_reclassify.py, tedana/workflows/t2smap.py, tedana/workflows/tedana.py
When we closed #747 I had made a comment that we might also want to log the version numbers of key modules used by tedana. This PR does that (plus identifies & corrects an omission from that PR)
- `dataset_description.json` includes the version numbers for all libraries specified in `project.toml`
-  `utils.get_system_info` is now `utils.get_system_and_version_info`. The previous line to get the python version was moved from tedana.py and ica_reclassify.py into this function and this function now compiles the version numbers for the other packages
- I wouldn't mind someone making sure I'm getting all the version numbers in a pythonic and not-too-inefficient way.
- In making the above changes, I noticed the `tedana` and `ica_reclassify` workflows …
=> Adding python library version numbers

docs/outputs.rst, pyproject.toml, tedana/bibtex.py, tedana/reporting/data/html/report_body_template.html, tedana/reporting/html_report.py, tedana/resources/references.bib, tedana/workflows/tedana.py
Closes #986
- The PR adds a new function `_bib2html()` that converts the contents of the bibtex file to an HTML string.
- The PR adds two dependencies to deal with the bibtex to HTML conversion.
=> Fix Bibtex rendering in reports

.github/dependabot.yml, .github/release-drafter.yml, .github/release.yml
Closes none.
- Add a dependabot config to automatically open PRs updating to new versions of dependencies. This will help us keep up to date _and_ flag any incompatible versions.
- Switch from release drafter to a changelog config. We can use PR labels to organize our release notes.
=> Add Dependabot config and switch Release Drafter to Changelog config

pyproject.toml
Closes #1028.
- Switch from setting minimum versions to maximum versions in the pyproject.toml. I used the versions installed from the last 3.12 CircleCI environment.
=> Pin maximum versions of dependencies in pyproject.toml

.pre-commit-config.yaml, tedana/decomposition/pca.py, tedana/io.py, tedana/selection/selection_nodes.py, tedana/selection/selection_utils.py, tedana/tests/test_integration.py, tedana/tests/test_io.py, tedana/workflows/ica_reclassify.py
Closes #974. Closes #1007.
- ica_reclassify Errors on Empty Input File fix
- This is the change @martinezeguiluz made in #1007 to fix the above issue plus merging my suggested update to that PR.
- I also merged in the last 3 months of updates to main and fixed resulting style issues.
- In trying to get this to pass the style check, I realized that pre-commit was using an older version of Black than CircleCI so I've updated the black version to use in `.pre-commit-config.yaml`
=> Fix error on empty input file & pre-commit updated to black version 24.2.0

tedana/reporting/static_figures.py
Closes #1042.
- Use `plot_stat_map` instead of identifying and plotting individual slices. This should address the potential orientation issues from #1042. It will also select the "best" slices for each component independently, so different components will have different slices rendered.
=> Improve component plots

pyproject.toml, tedana/reporting/dynamic_figures.py
Closes #1063
I've now had 3 people ask about crashes related to this issue I'd like to figure out a nice solution to this problem.
- Listed version numbers for bokeh in `pyproject.toml`
- Changed a few references from `circle` to `scatter` in `dynamic_figures.py`
- Since the tapping default was changed from `replace` to `xor` in `bokeh v3.4.0` it was possible to select more than one component at a time and that broke other functionality. This directly defines `models.TapTool(mode="replace")` instead of just listing `tap` with the default setting.
~~This no longer crashes, and the static report looks fine, but there is one annoying bug relating to the dynamic interactions. I'm not sure if this is due to the above changes or due to other changes in …
=> Fix dynamic reports with bokeh 3.4.0 problems

pyproject.toml
@pmolfese notified me of a crash when he ran tedana with nilearn v0.10.2:
```
File ".../python3.11/site-packages/nilearn/plotting/img_plotting.py", line 77, in _get_colorbar_and_data_ranges
raise ValueError('this function does not accept a "vmin" '
ValueError: this function does not accept a "vmin" argument, as it uses a symmetrical range defined via the vmax argument. To threshold the plotted map, use the "threshold" argument
```
In `static_figures.py` we are calling `nilearn.plotting.plot_stat_map` with the `vmin` option. Going through the nilearn releases, this was only added in v0.10.3  ( https://github.com/nilearn/nilearn/pull/3993 ). I really don't like setting our minimum nilearn version to something that was only released in January 2024. I'd welcome to code changes that address …
=> minimum nilearn to 0.10.3

tedana/reporting/static_figures.py
Closes #1095.
- Switch from the default 'continuous' resampling approach to 'nearest' in `plot_component`'s `plot_stat_map` call. This should stop non-diagonal images from being resampled to have low, non-zero values outside of the brain.
=> Use nearest-neighbors interpolation in `plot_component`

tedana/reporting/static_figures.py
Closes #1092.
- Filter out the "non-diagonal affine" warning when calling `plot_stat_map`.
=> Filter out non-diagonal affine warning

CONTRIBUTING.md
Closes #1118. I've already updated our branch protection rules to require only one approving review and to not dismiss "stale" reviews.
- Drop mention of prefixes for PR titles. We use tags these days.
- Say we only typically require one review, except for substantial PRs.
=> Require only one approving review for minor pull requests

docs/faq.rst, tedana/workflows/tedana.py
Closes none. This makes the formatting of params consistent.
- Add dash versions of `--ica-method` and `--n-robust-runs`. I didn't remove the underscore versions, but we should in the next major release.
=> Add dash versions of underscore params

tedana/tests/test_utils.py, tedana/utils.py, tedana/workflows/tedana.py
Closes #1150.
- Adds a function to check if the TE values given by a user are in ms. If they are not and are below 1, it assumes they are in seconds and they get updated by multiplying by 1000. If the values are a combination of higher than one and lower than one, the function raises an error.
- Adds a unit test to ensure the functionality is correct.
=> Add a function to check if TE values are in ms, otherwise update them

tedana/metrics/external.py
Closes #1152.
- Warn if the external regressors have NaNs.
- Back-fill (and forward-fill) cells with NaNs in the external regressors DataFrame.
=> Back-fill, then forward-fill, NaNs in external regressors

tedana/workflows/t2smap.py, tedana/workflows/tedana.py
Closes [I don't know if there was an issue open for this].
- T2smap workflow currently does not allow to overwrite files - but stops with runtime error if a file would be overwritten, asking to use the non-existing `--overwrite` argument. This PR solves that issue.
- I saw that in the tedana workflow parser, "overwrite" was added to the parser itself rather than to the "optional" parser group, so just quickly changed that, if desirable.
=> Add option to overwrite file (and write out extra files with "verbose") in T2smap workflow

.circleci/config.yml, tedana/io.py, tedana/tests/test_integration.py, tedana/workflows/ica_reclassify.py
Closes #1178.
- Adds verbose option to `ica_reclassify`
- Changes the way input files are registered from relative paths to absolute paths
- Adds `verbose = True` to the four echo integration test
=> Add verbose option to ica_reclassify to obtain denoised echo images

.circleci/config.yml
#1190 didn't quite work and now we're getting testing failures on other PR. Some tests were renamed, but we can't figure out how to get github to ignore the older test names. Everything is running fine on CircleCI
- Rename the new tests to match the names of the old tests
- Because the old names listed python versions as 310 instead of 3.10, the consistent way to do this was to replace all lists with python versions to just be 9, 10, 11, ... and then add `3` or `3.` as fixed text.
- Also changed the codecov orb to 5.3.0 to see if that fixes the separate codecov problem (It didn't fix that issue, but keeping at 5.3.0)
=> CircleCI testing fix

.circleci/config.yml
Closes #1192.
Me and @eurunuela tried to do a lot of things to get codecov working againa fter #1190 changed `.circleci/config.yml` to use version matrices. After nothing worked we decided to go back to the config from before #1190 that did work. We can then separately try to figure out how to switch back to version matrics without (again) breaking codecov interactions.
- Replaced `.circleci/config.yml` with the version that existed before #1190
=> Returns CircleCI config to before version matrics to fix codecov

tedana/tests/test_integration.py, tedana/workflows/tedana.py
Closes #1176.
We regularly receive user feedback that the masks calculated within tedana using `nilearns`'s `compute_epi_mask` sometimes removes too many potentially good voxels. Our documented recommendation is that users should provide their own masks.
It's useful to keep existing functionality so that tedana can run without a user-provided mask and we don't break backwards compatibility, but we should make the above message more explicit.
- Added text recommending users provide their own mask to the CLI and API descriptions for `mask`
- Changed an `LGR.info` to an `LGR.warning` with a more detailed message when an external mask is not provided
- Clarified an `LGR.info` message to state that, when a T2* map and no mask is provided, tedana assumes …
=> add warning for when tedana calculates mask

tedana/decomposition/pca.py, tedana/metrics/collect.py, tedana/reporting/static_figures.py, tedana/tests/data/nih_five_echo_outputs_verbose.txt, tedana/tests/test_metrics.py, tedana/workflows/tedana.py
Closes #1206 and reverts the changes in #748.
Closes #981 (Update: I realized it was really easy to also address this issue within this PR)
The signs of PCA & ICA components are flipped so that there are more positive vs negative values in the component weight maps. The maps were saved with the flipped values, but the time series in the mixing matrices were not. On a second look, after opening the issue, I realized that we actually were correctly flipping the mixing matrix in `collect.py` but `generate_metrics` was not returning the updated mixing matrix to be used elsewhere & saved.
I am labelling this a `breaking change` because the time series in the mixing matrix files might change, but it should not meaningfully alter results.
- …
=> Properly flip ICA mixing matrix time series

.circleci/config.yml, .github/workflows/python-publish.yml, pyproject.toml
I'm starting to look at #1185, and I'm not particularly interested in supporting Python 3.8 while doing so.
Please close if you have a reason to continue supporting EOL Python versions.
=> chore: Drop Python 3.8 support

tedana/io.py, tedana/metrics/external.py, tedana/tests/test_external_metrics.py, tedana/tests/test_io.py, tedana/tests/test_metrics.py, tedana/workflows/ica_reclassify.py, tedana/workflows/t2smap.py, tedana/workflows/tedana.py
Closes #1230.
- Add `--dummy-scans` parameter to tedana, t2smap, and ica_reclassify CLIs. The default is 0, so this doesn't change the default behavior.
- Add `dummy_scans` argument to `load_data` and `load_validate_external_regressors`. I made it so the dummy scans may or may not already be removed from the external regressors.
- Require argument names in calls to `load_validate_external_regressors` and `validate_extern_regress`. These are internal functions, so I think it just makes it clearer what arguments are being passed in, and it shouldn't affect the user experience at all.
=> Add `--dummy-scans` parameter to CLIs

tedana/decomposition/pca.py
Closes # 1233.
I noticed that ICA components where different after #1212 was merged. @tsalo noticed the bug was that, in `decomposition.tedpca` we flipped the component mixing matrix time series in `collect.generate_metrics` but, `voxel_comp_weights` was not flipped. This slipped past because we were focused on this change for ICA and, for ICA and PCA, the weight map is calculated saved to a file within `collect.generate_metrics` & we didn't notice that a the weight map separately calculated in `decomposition.tedpca` was the one that was returned & used.
- The "optimal sign" values (1 or -1) calculated in `collect.generate_metrics` is used to flip the signs for components in `voxel_comp_weights`
**Note 1** Please take a look to confirm nothing else …
=> Fixing unflipped PCA component weights

tedana/metrics/external.py, tedana/tests/test_external_metrics.py, tedana/tests/test_metrics.py
Turns out https://github.com/ME-ICA/tedana/pull/1163 did not fix the issue, because the modified dataframe is never returned to the workflow.
Quick fix, but adding tests would be better.
=> Fix NaNs in external regressors, take 2
