.travis.yml
circle.yml
tedana/interfaces/data.py
tedana/interfaces/t2smap.py
tedana/interfaces/tedana.py
tedana/tests/test_tedana.py
tedana/utils/utils.py
tox.ini

Make sure we're getting consistent results !

[TST] Resolve np.allclose error in integration testing

---

CONTRIBUTING.md
Dockerfile
circle.yml
docs/contributing.rst
docs/index.rst
docs/installation.rst
docs/introduction.rst
docs/usage.rst

The documentation could use some major updating. Starting here to include the style guide for submitting PRs, as discussed in #7.

[DOC] Update docs

---

Dockerfile
circle.yml

I confused @rmarkello and had him accidentally open a PR on my fork instead of the main repo ! Moving it over here.

Merge in @rmarkello PR

---

README.md
tedana/cli/run.py
tedana/interfaces/tedana.py
tedana/tests/test_tedana.py

This should make it easier to use tedana in Python.
Also:
- Split arguments in tedana.main
- Switch from calling os.system to using shutil and specific os
functions
- Change variable dirname to out_dir
- Use full paths when saving files. Should eliminate need to chdir into
out_dir halfway through the function
- Add docstring for main

[WIP, ENH] Allow separate data files as input.

---

.codecov.yml

[ENH] Add coverage threshold

---

.github/pull_request_template.md

Fixes #7 
Changes proposed in this pull request
- Adds a pull request template !

[ENH] add PR template

---

.github/pull_request_template.md
tedana/selection/select_comps.py
tedana/tests/test_utils.py
tedana/utils/utils.py

Closes #33.
- Parses gii files supplied in an `*.[L,R].fun.gii` format
- Skips spatial filtering for gii files in `sel_comps`

[FIX] Update gii file handling

---

tedana/cli/run_tedana.py

- Now that workflows are initialized a level above (i.e., `tedana.workflows.tedana` no longer points to the `tedana` submodule and instead points to the function in `tedana.workflows.tedana.tedana`), the CLI scripts need to be updated. Apparently `run_t2smap` already was updated, but `run_tedana` wasn't.

[FIX] Fix CLI.

---

requirements.txt
tedana/model/monoexponential.py
tedana/tests/test_model_monoexponential.py
tedana/tests/utils.py

- Add test for tedana.model.monoexponential.fit_decay that compares results to results used for integration test of full workflow.
- Add smoke test for tedana.model.monoexponential.fit_decay_ts that just runs the function and checks that the resulting numpy arrays are in the right shape.

[TST] Add tests for tedana.model.monoexponential

---

docs/index.rst
tedana/__init__.py

- Add module-level duecredit citation for Zenodo release to tedana/__init__.py
- Add citations for Kundu et al. (2013) and Zenodo release to RTD index page.
- Add instructions for generating citations with duecredit to RTD index page.

[DOC] Add citations for Zenodo release to code and docs.

---

docs/contributing.rst

(Re-)Closes #51.
- Documentation only update&mdash; removes docker reference in RTD contributing docs

[DOCS] Remove docker reference in contributing

---

CONTRIBUTING.md

Closes #27.
- Updates the contributing file to reference gitter room

[DOC] Add discussion of gitter room

---

circle.yml
tedana/tests/test_tedana.py
tedana/utils/utils.py
tedana/workflows/tedana.py

- Sets a unique name for each TED directory, so the wrong pcastate is not accidentally loaded

[FIX] Add fname to TED dirname

---

tedana/workflows/tedana.py

- Adds extensions for filenames written by utils.filewrite()
- Patches CI testing

[FIX] add extensions in fnames for filewrite

---

.zenodo.json

[FIX] Lint zenodo.json

---

tedana/utils/utils.py

- If non-NIFTI files (e.g., BRIK/HEAD) are provided, don't complain and just handle it as needed. This involves re-writing `utils.filewrite` and `new_nii_like` to accommodate the fact that `ref_img` may not be a nifti image.

[FIX] Accept non-NIFTI files without complaining

---

docs/multi-echo.rst

[DOC] Update multi-echo.rst

---

README.md
docs/contributing.rst
docs/index.rst
docs/roadmap.rst

Corrects bad formatting in merge of #151.

[DOC] RST formatting fixes for roadmap, contributing

---

tedana/viz.py

Closes no issue
- Center Color bar at zero, per dev call request.
Before:
After:

[FIX] center component map at zero

---

CONTRIBUTING.md

Partially closes #258
- Adds policy for stale issues to CONTRIBUTING

[DOC] Add stale issue policy to CONTRIBUTING

---

README.md

Closes #285 .
- Change source (de)activate to conda (de)activate

[DOC] Changes source->conda for env (de)activate

---

docs/multi-echo.rst

Closes None :disappointed: 
- Updates multi-echo.rst to explain why researchers might use multi-echo fMRI
- Updates multi-echo.rst to include the Cam-CAN dataset.

[DOC] Adds information on why we use multi-echo

---

CONTRIBUTING.md

Closes #257 by adding to CONTRIBUTING guidelines
- Adds description of paused tag to CONTRIBUTING

[DOC] Add Paused label description to CONTRIBUTING

---

.circleci/config.yml
.circleci/tedana_outputs_verbose.txt
tedana/workflows/tedana.py

Closes #169 
- Makes log name tedana_run so that it is static
- Detects name collisions and appends _old until there is no collision

[ENH] Adds static logging filename

---

docs/conf.py

Closes #289 .
- Changes copyright year max to 2019

[DOC] Updates copyright year

---

CONTRIBUTING.md

Closes #221 .
- Adds a short sentence requesting that people do not open draft pull requests at this time.

[DOC] Requests no Draft PRs in CONTRIBUTING

---

docs/index.rst

Addresses issue #290 
- This is just a brief update to the homepage file
- In the about section, it redirects the users to other pages depending on what information they are looking for

[DOC] Update homepage > "about tedana" to redirect readers to relevant page

---

docs/multi-echo.rst

Closes part of #290 
- In the multi-echo fMRI sections, I have just included more information about what regular fMRI EPI give
- I had planned to add more to the "Why use multi-echo?" but it was already addressed in a previous PR! 
- Link users to pipeline>optimal combinations, and fixed link to the paper in "Why use multi-echo?" section

[DOC] Addition to the multi-echo fMRI section to include more background

---

.circleci/config.yml

Closes #328  .
- Modifies URL for fetching three-echo dataset to new file

[FIX] Modifies three-echo dataset url to new location

---

tedana/tests/test_combine.py
tedana/tests/test_decay.py
tedana/tests/test_selection.py

Closes None .
- Updates the comments in /test/ to reflect refactoring changes

[DOC] Corrects doc after refactor

---

docs/multi-echo.rst

Related to discussion in  #340 and #336 
- Two paragraphs are added to multi-echo.rst to discuss "Recommendations on multi-echo use for someone planning a new study" This addition is in response to several requests at OHBM2019. Several people should read this to make sure they agree with my recommendations!
- I also added stubs to this file where we can add information on "Available multi-echo fMRI sequences for multiple vendors" and "Multi-echo preprocessing software." I'm working on the first one, but I figured it was good to make a public place holder in case anyone sees it and asks to contribute. For the second one, the necessity of the other preprocessing pipelines is also mentioned in usage.rst, but it's the type of information that might be …

[DOC] Adding recommendations into multi-echo.rst

---

README.md
docs/index.rst

Closes no open issues.
- Added a badge to sign up to the newsletter and mentioned it in the getting involved section of the README
- Added a badge for the newsletter in the RTD home page (I don't know rst so I might have made a mistake there!)
- This commit also has some formatting changes to the README because I'm weirdly picky about having new sentences on new lines 😬

[DOC] Add newsletter to README file & RTD homepage

---

docs/multi-echo.rst

Closes #347 
- changes "data" to "of"
- changes "recommended" to "recommend"

[DOC] Fix small typos in multi-echo.rst documentation

---

.circleci/config.yml
.codecov.yml

Closes None. I thought that the CodeCov report generation problem from #368 would be resolved by merging the PR, but it wasn't. Sorry about that!

[FIX, TST] Fix CodeCov report upload

---

CONTRIBUTING.md

Closes #343  .
- Adds small doc patch procedure
-

[DOC] Allows small doc patches

---

.circleci/config.yml
.circleci/tedana_outputs_verbose.txt
tedana/workflows/tedana.py

Closes #361 per my [proposal](https://github.com/ME-ICA/tedana/issues/361#issuecomment-530128947) .
- Makes logfile name `tedana_<ISO>.txt`
- Removes logfile name from checked inputs
- WIP will add unit testing to `/tests/` to verify that logfiles are generated.

[FIX][ENH][TST] Adds datetime logfile and removes it from outputs, fixes stream handling

---

.circleci/tedana_outputs_verbose.txt
docs/outputs.rst
tedana/workflows/tedana.py

Closes #339 .
- Stop writing the file
- Remove file reference from readthedocs "Outputs of tedana"

[ENH] Stop writing __meica_mix.1D

---

tedana/workflows/tedana.py

Closes # .
- Added a version tag
-

Added version argument

---

.github/stale.yml

Closes #258
- Adds [stale-bot](https://probot.github.io/apps/stale/) to the tedana repository
- Configures stale-bot such that issues are closed after 3 months of inactivity

enh: add stale-bot

---

tedana/decay.py
tedana/tests/test_decay.py

Closes #470. Fixes a bug introduced in #468.
- Use the set of good echoes to preallocate arrays instead of all echoes.

[FIX] Fix array preallocation in decay-fitting functions

---

tedana/decomposition/pca.py
tedana/workflows/tedana.py

Closes #486  .
- Removes MLE PCA
-

[REF] Removes mle option

---

tedana/metrics/kundu_fit.py

Closes #484.
- Eliminate confusing variable copy by assigning to a new variable and using that.

[REF] Remove confusing variable copy

---

tedana/tests/data/cornell_three_echo_outputs.txt
tedana/tests/data/nih_five_echo_outputs_verbose.txt
tedana/tests/test_integration.py

Closes None.
- Test gscontrol, png_cmap, and re-running.

[TST] Expand parameters tested in integration tests

---

codecov.yml

Closes #489  .
- Removes tests from codecov checks
-

[TST] Remove testing directory from coverage tests

---

README.md
docs/index.rst

Closes #533.
- Add "Average time to resolve an issue" badge to README.
- Add "Percentage of issues still open" badge to README.
- Add "Average time to resolve an issue" badge to RTD index page.
- Add "Percentage of issues still open" badge to RTD index page.

[DOC] Add "is it maintained" badges

---

tedana/decomposition/ma_pca.py
tedana/tests/test_mapca.py

Closes #522 .
- Adds unit tests to almost every function in `ma_pca.py`.
- Fixes bug in `ma_pca.py`.

[FIX,TST] Adds unit tests for ma_pca functions and fixes a bug in ma_pca

---

tedana/workflows/t2smap.py

Closes #544.
- Use the explicit mask if it is provided.

[FIX] Use mask, when provided, in t2smap workflow

---

tedana/combine.py

Closes #558.
- Replace data average over time with SNR (data average over time divided by data standard deviation over time) in PAID combination method.

[FIX] Use SNR for PAID instead of mean data

---

docs/acquisition.rst

Include description for Philips users
Closes # .
add availability of ME-EPI sequences on Philips scanners
-
-

Update acquisition.rst to include information for Philips scanners

---

CONTRIBUTING.md
README.md
docs/developing.rst

Closes #532. I noticed the issue went stale and it seemed easy enough to address, so I took a crack at it.
- Recommend using `[all]` option when installing tedana in editable mode for development.
- Rename "Developer Guidelines" page to "Developer guidelines" to match general title-case pattern.
- Link to "Developer guidelines" page in README.

[DOC] Include [all] in developer setup install guidelines

---

docs/approach.rst

Closes #547 .
- Remove confusing lines.
- Mention why we have three options.
- Add links to Wikipedia for each option as it's probably the easiest way for users to have an idea of what each option does.
- Add a note that states it is a data-driven approach and the results might not be perfect (that's also why we provide three options).

[DOC] Rewrite new PCA section

---

.github/ISSUE_TEMPLATE/config.yml

Closes #647.
- Add link to NeuroStars to issue template selection page.

[DOC] Add NeuroStars question link

---

.zenodo.json

Closes None, but stems from #669.
- Add new contributors to the Zenodo file.

[MAINT] Add new contributors to Zenodo file

---

.circleci/config.yml
.github/workflows/python-publish.yml

Closes None, but references #596.
- Add GitHub Action for deployment.
- Remove deployment step from CircleCI.

Set up GitHub deployment Action

---

setup.py

[MAINT] Switches to md type

---

tedana/decomposition/ma_pca.py
tedana/tests/data/cornell_three_echo_outputs.txt

Closes None. The goal of this PR is to harmonize our approach in `tedana` with the approach in `mapca`. I figure, if the results from these changes are the same as the results in #641, we can merge this to have it in our history and then overwrite the changes with #641 very quickly.
- Normalize data over time in ma_pca to match the changes made in ME-ICA/mapca.

[REF] Normalize over time in MAPCA

---

README.md
docs/installation.rst

I noticed that mapca isn't listed in the current dependencies, so I added it.
- Added mapca to the list of dependencies in README.md
- Not sure if there's anywhere else mapca should be listed as a dependency.

[DOC] Added MAPCA to list of dependencies

---

.circleci/config.yml
README.md
docs/installation.rst
tedana/info.py

Closes #706 and #707.
- Drop support for Python 3.5.
- Remove tests for Python 3.5.
- Add support for Python 3.8 and 3.9.
- Add tests for Python 3.8 and 3.9.
Once this is merged, we'll need to update our required checks under the `main` branch's protection rules.

[MAINT] Drop 3.5 support and begin 3.8 and 3.9 support

---

tedana/info.py

Testing dependency versioning to ease interactions with fMRIPrep.

[FIX] Bumps (down) sklearn and scipy

---

.github/workflows/python-publish.yml

Closes None
- Modifies GitHub Actions to upload to PyPI on release *publish* specifically
-

[MAINT] Modifies actions to run on release publish

---

tedana/metrics/dependence.py

[ENH] Allows iterative clustering

---

tedana/metrics/collect.py
tedana/resources/config/metrics.json

Closes #735.
- Move metric dependency dictionaries in `tedana.metrics.collect` into a new configuration json file.

[REF] Replace metric dependency dictionaries with json file

---

.circleci/config.yml

Closes none.
This PR is just checking if changing the CircleCI config will fix the builds or not.

[FIX] Update apt in CircleCI

---

docs/multi-echo.rst

Closes #775.
- Add link to the EuskalIBUR dataset to our multi-echo datasets documentation.

[DOC] Add link to EuskalIBUR dataset in documentation

---

docs/multi-echo.rst

Closes #755.
- Replace `tedana` with "multi-echo denoising" in recommendations for preprocessing multi-echo data.
- Add a step about motion correction.

[DOC] Generalize preprocessing recommendations

---

docs/multi-echo.rst

Closes #791  .
- Adds CMN video to resources
-

[DOC] Adds NIMH CMN video

---

README.md

References #796. Not sure if I want to close it from this PR.
- Update the link to the developer guidelines within our documentation in the README.

[DOC] Fix link to developer guidelines in README

---

tedana/io.py
tedana/tests/test_io.py

Closes #858  .
- adds prep_data_for_json to inspect a dictionary for ndarrays and change them into lists for saving data to JSON
-

[FIX] Add function to prep data for JSON serialization

---

docs/multi-echo.rst

Closes #784, closes #787, closes #788, closes #789, closes #790, closes #866. These are all good first issues, but they almost all been open for over a year, so I don't think anyone is planning to address them.
- Add links to several multi-echo datasets.

Add links to several multi-echo datasets

---

docs/denoising.rst

Closes #913.
- Copy @eurunuela's corrected denoising code into the documentation.

Fix example code in denoising documentation

---

docs/approach.rst
docs/outputs.rst

I'm going through the docs to refresh my understanding of ME-ICA, and noticed that the output file name was not updated there.

[DOC] desc-optcomDenoised -> desc-denoised

---

docs/multi-echo.rst

Closes none.
- Add new datasets from `open-multi-echo-data` to list of datasets in tedana's documentation.

Update list of multi-echo datasets

---

docs/multi-echo.rst

Closes none.
- Link out to the open multi-echo data website I've been working on.

Link to the open-multi-echo-data website

---

docs/index.rst

Closes #676.
- Link out to release notes from sidebar in docs.

Add external link to release notes

---

docs/multi-echo.rst

Fix a typo in the documentation.

Very small typo fix in documentation

---

tedana/reporting/data/html/report_body_template.html

Closes #1050.
- Remove the fixed height from the style of each image
- Add max width to each image
- Add window width-dependent width to each image

Enforce equal figure widths in HTML report and make them adjustable by window size

---

.circleci/config.yml
tedana/workflows/tedana.py

closes #1192.
Proposed changes:
- Several changes to `.circleci/config.yml` to get the codecov orb again working through CircleCI

Fixing codecov automation

---

.circleci/config.yml

Closes #1189 
- Uses version matrices instead of duplicating code to set a new version.
- Uses single version for integration tests.
- Uses all version in matrix for unit tests.

Change CircleCI versioning to use version matrices

---

.circleci/config.yml
tedana/utils.py
tedana/workflows/ica_reclassify.py
tedana/workflows/t2smap.py
tedana/workflows/tedana.py

Closes #1198
- Adds a new function to `utils.py` to avoid rewriting the same logs in all 3 workflows.
- Calls the `utils.log_newsletter_info()` at the end of each workflow.

Add logging for tedana newsletter subscription information

---

tedana/reporting/data/html/report_body_template.html
tedana/reporting/data/html/report_carpet_buttons_template.html
tedana/reporting/data/html/report_head_template.html
tedana/reporting/data/html/report_info_table_template.html
tedana/reporting/html_report.py
tedana/reporting/static_figures.py
tedana/tests/test_integration.py

Closes #1204 and closes #1084 .
- Replaces assert for a warning
- T2* images are always generated
- S0 images are only generated if the S0 file exists

Use Jinja2 to populate reports and deal with empty spaces when figures aren't added
